export const products = [
//   {
//     name: "Dell Latitude 7450",
//     sku: "LAP-001",
//     description: "Business Laptop",
//     price: 75000,
//     quantity: 20,
//     minStock: 5,
//     category: "Laptops",
//     supplier: "Dell India",
//   },
  {
    name: "HP ProBook 450",
    sku: "LAP-002",
    description: "HP Business Laptop",
    price: 68000,
    quantity: 18,
    minStock: 5,
    category: "Laptops",
    supplier: "HP India",
  },
  {
    name: "Lenovo ThinkPad E14",
    sku: "LAP-003",
    description: "Lenovo Laptop",
    price: 72000,
    quantity: 15,
    minStock: 5,
    category: "Laptops",
    supplier: "Lenovo India",
  },
  {
    name: "Asus VivoBook 15",
    sku: "LAP-004",
    description: "Student Laptop",
    price: 56000,
    quantity: 25,
    minStock: 5,
    category: "Laptops",
    supplier: "Asus India",
  },
  {
    name: "Acer Aspire 7",
    sku: "LAP-005",
    description: "Gaming Laptop",
    price: 65000,
    quantity: 10,
    minStock: 3,
    category: "Laptops",
    supplier: "Acer India",
  },
  {
    name: "Logitech Wireless Mouse",
    sku: "ACC-001",
    description: "Bluetooth Mouse",
    price: 1200,
    quantity: 100,
    minStock: 20,
    category: "Accessories",
    supplier: "Logitech India",
  },
  {
    name: "Seagate 1TB HDD",
    sku: "STO-001",
    description: "External Hard Disk",
    price: 4500,
    quantity: 40,
    minStock: 10,
    category: "Storage Devices",
    supplier: "Seagate India",
  },
  {
    name: "WD 500GB SSD",
    sku: "STO-002",
    description: "SATA SSD",
    price: 5200,
    quantity: 35,
    minStock: 10,
    category: "Storage Devices",
    supplier: "Western Digital",
  },
  {
    name: "Canon LBP2900",
    sku: "PRI-001",
    description: "Laser Printer",
    price: 14500,
    quantity: 8,
    minStock: 2,
    category: "Printers",
    supplier: "Canon India",
  },
  {
    name: "Samsung 24 Monitor",
    sku: "MON-001",
    description: "24-inch IPS Monitor",
    price: 11500,
    quantity: 12,
    minStock: 3,
    category: "Monitors",
    supplier: "Samsung India",
  },
];