import dashboardRepository from "../repositories/dashboardRepository.js";
import { generateFinancialExcel } from "../utils/financialExcel.js";
import { generatePdf } from "../utils/pdfGenerator.js";

class ReportService {
  async generateFinancialReport(filters: {
    startDate?: Date;
    endDate?: Date;
  } = {}): Promise<Buffer> {
    const summary =
      await dashboardRepository.getFinancialSummary(filters);

    const startDate = filters.startDate
      ? filters.startDate.toISOString().slice(0, 10)
      : "All time";

    // The service receives an exclusive end date.
    const endDate = filters.endDate
      ? new Date(
          filters.endDate.getTime() - 24 * 60 * 60 * 1000
        )
          .toISOString()
          .slice(0, 10)
      : "Present";

    const escapeHtml = (value: string): string =>
      value.replace(/[&<>"']/g, (character) => {
        const entities: Record<string, string> = {
          "&": "&amp;",
          "<": "&lt;",
          ">": "&gt;",
          '"': "&quot;",
          "'": "&#39;",
        };

        return entities[character] ?? character;
      });

    const html = `
      <!DOCTYPE html>
      <html lang="en">
        <head>
          <meta charset="UTF-8" />
          <title>Elite Inventory Financial Report</title>
          <style>
            body {
              font-family: Arial, sans-serif;
              color: #1f2937;
              padding: 20px;
            }

            h1 { color: #1d4ed8; }
            .period { color: #6b7280; margin-bottom: 28px; }

            table {
              width: 100%;
              border-collapse: collapse;
              margin-top: 20px;
            }

            th, td {
              border: 1px solid #e5e7eb;
              padding: 14px;
              text-align: left;
            }

            th { background: #eff6ff; }
            .profit { color: #15803d; font-weight: bold; }
            footer {
              margin-top: 36px;
              color: #6b7280;
              font-size: 12px;
            }
          </style>
        </head>
        <body>
          <h1>Elite Inventory</h1>
          <h2>Financial Summary Report</h2>

          <p class="period">
            Period: ${escapeHtml(startDate)} to ${escapeHtml(endDate)}
          </p>

          <table>
            <thead>
              <tr><th>Metric</th><th>Amount (currency units)</th></tr>
            </thead>
            <tbody>
              <tr>
                <td>Revenue</td>
                <td>${(summary.revenue)}</td>
              </tr>
              <tr>
                <td>Cost of Goods Sold (COGS)</td>
                <td>${(summary.cogs)}</td>
              </tr>
              <tr>
                <td>Gross Profit</td>
                <td class="profit">${(summary.grossProfit)}</td>
              </tr>
              <tr>
                <td>Recorded Sales Transactions</td>
                <td>${summary.salesTransactions}</td>
              </tr>
            </tbody>
          </table>

          <footer>
            Generated by Elite Inventory. This report includes sales
            transactions with complete financial snapshots.
          </footer>
        </body>
      </html>
    `;

    return generatePdf({
      title: "Elite Inventory Financial Report",
      html,
    });
  }

    async generateFinancialExcelReport(filters: {
      startDate?: Date;
      endDate?: Date;
    } = {}): Promise<Buffer> {
      const summary =
        await dashboardRepository.getFinancialSummary(filters);
    
      return generateFinancialExcel({
        summary,
        ...(filters.startDate !== undefined
          ? { startDate: filters.startDate }
          : {}),
        ...(filters.endDate !== undefined
          ? { endDate: filters.endDate }
          : {}),
      });
    }
}

export default new ReportService();